### ISSUE TITLE
Tiles aren't being loaded pixel by pixel but tile by tile

### ISSUE THREAD

**Issue by hoichael** [Noah2610/deathfloor#16]
Same problem we've already had during the development of stabman

**Comment by Noah2610** [comment]
You mean, when tiles come onto the screen, you can see them appearing?

**Comment by hoichael** [comment]
Yes, and disappearing when going off screen.


[https://imgur.com/c5SXcbe](url)

**Comment by Noah2610** [comment]
Yeah, I just need to increase the loading distance of the camera.
