### ISSUE TITLE
Enemies invisible

### ISSUE THREAD

**Issue by hoichael** [Noah2610/deathfloor#37]
Check current master branch

**Comment by Noah2610** [comment]
@hoichael The generated spritesheet RON file looks wrong.
If one yellow enemy sprite is 24x32, then generate with
```
sprongen -A master -s 24x32 enemy_yellow_normal1.png
```
(commited sprites are configured with 3x3)

To verify that the spritesheet RON is properly generated, add the `-p` flag to make the RON file human-readable, like
```
sprongen -A master -s 24x32 enemy_yellow_normal1.png -p
```
Then you can see if the RON looks alright or nah.

I'll commit the fixed spritesheet RON in a moment.
