### ISSUE TITLE
Basic enemy death animation / bullet destroy animation

### ISSUE THREAD

**Issue by hoichael** [Noah2610/deathfloor#42]

**Comment by Noah2610** [comment]
@hoichael 

Add `Death` animation of type `Once` to entities, to make them play that animation when their health hits 0, before they are deleted.
https://github.com/Noah2610/deathfloor/blob/da8b02edfd23d742efdd2b46ad3f2837b23cd761/resources/settings/enemies/dev/dev.ron#L35

It's important that the animation type is `Once` and not `Cycle`, with `Cycle` the death animation would loop and the entity would never get deleted.
