### ISSUE TITLE
Multiple hitboxes on the same entity for different collision tags

### ISSUE THREAD

**Issue by hoichael** [Noah2610/deathfloor#59]
Would that be possible?

**Comment by Noah2610** [comment]
@hoichael So on one entity, multiple hitboxes each with its own collision tag?
That's not currently possible and would require a lot of rewriting. All entity configs would also have to be adjusted.
I really wouldn't want to do this, unless you think it would be worth it.

**Comment by hoichael** [comment]
nvm then
