### ISSUE TITLE
Jump pad

### ISSUE THREAD

**Issue by Noah2610** [Noah2610/deathfloor#8]
Player is yeeted upwards when walking over jump pad.

**Comment by Noah2610** [comment]
## Open Questions
### How would you place a jumppad in tiled?
As an _object_ or as a _tile_?

- A _tile_ would already have a sprite associated, but can't have a custom size (has tile size).
  You would still be able to place multiple tiles next to each other to make bigger jumppads.
- An _object_ would need to have a sprite associated somewhere else
  (through config file or tiled properties). But it could have any size.

I would say as a _tile_, for now at least. Unless we already need custom-sized jumppads.

### How would you define a tile/object to _be_ a jumppad?
- With the `type` field?
  With the type field, it could have associated data in its config file (such as yeet strength).
  We could still make the strength overwritable through tiled properties.
- Or with a custom property?
  With a custom property, yeet strength could only be specified
  as _another_ (or the same) property.

I would say with the `type` field.

@hoichael thoughts?

**Comment by hoichael** [comment]
Seems fine, I don't see any problems with placing jumppads as a `tile` and defining them through their `type` should enable all the customization we need.

**Comment by Noah2610** [comment]
@hoichael 👍

**Comment by Noah2610** [comment]
@hoichael
